### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by nancy12Ru** [omerjerk/RemoteDroid#9]
I install the app in my two rooted phone, and start the server, start the client, input the ip to the client, then it doesn't show the toast that connect failed,but the logcat in Android Studio shows the Log:
java.net.ConnectException: failed to connect to /192.168.43.45 (port 80): isConnected failed: ECONNREFUSED (Connection refused)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:238)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at java.nio.SocketChannelImpl.finishConnect(SocketChannelImpl.java:277)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:802)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err: Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
11-21 22:00:23.919 23625-24374/in.umairkhan.remotedroid W/System.err:     at libcore.io.IoBridge.isConnected(IoBridge.java:223)

**Comment by nancy12Ru** [comment]
when I change the port that listens, it works. however the operation is not accurate.

**Comment by omerjerk** [comment]
@nancy12Ru Could you explain what you really mean?

I don't maintain this project but I can definitely provide any possible assistance. :)

**Comment by nancy12Ru** [comment]
Thank you for replying me. :)
I mean that when I change the port of server listens , (I change 6094 to 80) , and connect , which have a toast "connect completed".
Then  the phone as server phone's screen will become black . 
And  the logcat give the message like the top I given.
As a result, operating the server phone  will not make the client phone  having the same operation.

**Comment by hailianglone** [comment]
I met the same problem as you.
excuse me， your app is ok?

**Comment by omerjerk** [comment]
Hey!

I'll look into this issue definitely now.

**Comment by chen-xiao-dong** [comment]
Hello,
When I click to start the client side,it prompts to fill the ip address,I check the server device which is sharing hotpot and where to get the ip address for the server device？
